"""mus_engine: motor de Mus determinista según el Reglamento de Juego de la FEM.

API pública. Las fases aún no implementadas (partida, acciones, observaciones,
replay) se irán exponiendo aquí.
"""

from mus_engine.cards import Card, Deck, Rank, RankingPolicy, Suit
from mus_engine.config import DeckType, GameConfig
from mus_engine.errors import (
    GameFinishedError,
    GameNotStartedError,
    IllegalActionError,
    InvalidBetError,
    InvalidCardError,
    InvalidConfigError,
    InvalidDeckError,
    InvalidDiscardError,
    InvalidPlayerError,
    InvalidStateError,
    InvariantViolationError,
    MusEngineError,
    NotYourTurnError,
    PrivateInformationError,
)
from mus_engine.events import EventEnvelope, Visibility
from mus_engine.game import (
    AcceptAction,
    Action,
    AmountRange,
    BetAction,
    CutMusAction,
    DiscardAction,
    Game,
    GameRecord,
    GameState,
    HandState,
    LegalActions,
    MusAction,
    Observation,
    OrdagoAction,
    PassAction,
    Phase,
    RaiseAction,
    RejectAction,
    RulesEngine,
)
from mus_engine.players import (
    Player,
    SeatId,
    Table,
    Team,
    TeamId,
    are_teammates,
    next_player,
    partner,
    previous_player,
    team_of,
)
from mus_engine.replay import GameReplay
from mus_engine.rng import Rng
from mus_engine.rules import (
    ChicaEvaluator,
    GrandeEvaluator,
    JuegoEvaluator,
    LanceResult,
    LanceType,
    ParesCategory,
    ParesEvaluator,
    PuntoEvaluator,
    resolve,
)
from mus_engine.scoring import GameScore, ScoringEngine

__all__ = [
    "AcceptAction",
    "Action",
    "AmountRange",
    "BetAction",
    "Card",
    "ChicaEvaluator",
    "CutMusAction",
    "Deck",
    "DeckType",
    "DiscardAction",
    "EventEnvelope",
    "Game",
    "GameConfig",
    "GameFinishedError",
    "GameNotStartedError",
    "GameRecord",
    "GameReplay",
    "GameScore",
    "GameState",
    "GrandeEvaluator",
    "HandState",
    "IllegalActionError",
    "InvalidBetError",
    "InvalidCardError",
    "InvalidConfigError",
    "InvalidDeckError",
    "InvalidDiscardError",
    "InvalidPlayerError",
    "InvalidStateError",
    "InvariantViolationError",
    "JuegoEvaluator",
    "LanceResult",
    "LanceType",
    "LegalActions",
    "MusAction",
    "MusEngineError",
    "NotYourTurnError",
    "Observation",
    "OrdagoAction",
    "ParesCategory",
    "ParesEvaluator",
    "PassAction",
    "Phase",
    "Player",
    "PrivateInformationError",
    "PuntoEvaluator",
    "RaiseAction",
    "Rank",
    "RankingPolicy",
    "RejectAction",
    "Rng",
    "RulesEngine",
    "ScoringEngine",
    "SeatId",
    "Suit",
    "Table",
    "Team",
    "TeamId",
    "Visibility",
    "are_teammates",
    "next_player",
    "partner",
    "previous_player",
    "resolve",
    "team_of",
]
